title: Mamatzone
author: smallzero
email: agus.rochmad@hotmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Jadilah Profesional Sejati dalam bidang apa yang anda tekuni. Tinggalkan jejak-jejak prestasi. 
  
  [Prof. DR. Ing. H. Bacharuddin Jusuf Habibie]
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Agus Rochmad Tri Raharjo  
  tagline: DevOps. Software Engineer
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content

  # generate social links in footer
  social_links:
    twitter: mamatzone
    github:  smallzero
    linkedIn: in/rochmad
    rss: rss
    # dribbble: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # facebook: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: jekyll-theme-minimal

remote_theme: thelehhman/plainwhite-jekyll

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
